name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  # Registry for the container image
  CONTAINER_IMAGE_REGISTRY: ghcr.io
  # Name of the container image
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  # URL to the repository source code
  SOURCE_URL: "https://github.com/${{ github.repository }}"
  # Description of the base container image
  CONTAINER_IMAGE_DESCRIPTION: "Base container image for the Forgescript Mythic service"
  # License for the base container image
  CONTAINER_IMAGE_LICENSE: BSD-3-Clause

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  image:
    name: Build and push the base container image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set the container image fully qualified url
        run: echo "CONTAINER_IMAGE_URL=${CONTAINER_IMAGE_URL,,}" >> ${GITHUB_ENV}
        env:
          CONTAINER_IMAGE_URL: ${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the container image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.CONTAINER_IMAGE_URL }}
          push: true
          labels: |
            org.opencontainers.image.source=${{ env.SOURCE_URL }}
            org.opencontainers.image.description=${{ env.CONTAINER_IMAGE_DESCRIPTION }}
            org.opencontainers.image.licenses=${{ env.CONTAINER_IMAGE_LICENSE }}
          build-args: |
            GIT_HASH=${{ github.sha }}
            EMBED_VERSION=${{ github.ref_name }}

  release:
    name: Create new repository release
    runs-on: ubuntu-latest

    needs:
      - image

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create a new Github release
        env:
          GIT_TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh release create $GIT_TAG -d -t "Forgescript $GIT_TAG" -n "" --verify-tag
